_wandb:
    value:
        cli_version: 0.24.0
        e:
            19805qofepwfjzismphlprpotzfcjufc:
                codePath: s4_debugging_and_logging/exercise_files/vae_mnist_working.py
                codePathLocal: vae_mnist_working.py
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "1081101176832"
                        used: "12381323264"
                email: s234855@dtu.dk
                executable: /workspaces/dtu_mlops/.venv/bin/python3
                git:
                    commit: 390df6a62e445cc087d4d79aac4bb6bbb6c2c87b
                    remote: https://github.com/SkafteNicki/dtu_mlops
                host: 3336d02e49e1
                memory:
                    total: "3948138496"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.41
                program: /workspaces/dtu_mlops/s4_debugging_and_logging/exercise_files/vae_mnist_working.py
                python: CPython 3.11.14
                root: /workspaces/dtu_mlops/s4_debugging_and_logging/exercise_files
                startedAt: "2026-01-17T20:50:09.877507Z"
                writerId: 19805qofepwfjzismphlprpotzfcjufc
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 100
epochs:
    value: 2
hidden_dim:
    value: 400
latent_dim:
    value: 20
lr:
    value: 0.001
x_dim:
    value: 784
